server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CineMaster;encrypt=false;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenthingochuyen11.1cbq@gmail.com
    password: zxob assm mzka mmhc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
