server:
  port: 8081
  servlet:
    context-path: /demo   # Giữ nguyên

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CineMaster;encrypt=false;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenthingochuyen11.1cbq@gmail.com
    password: zxob assm mzka mmhc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 989990507917-jmah0sq1bglebpg2kmh8gmkf2r7150ol.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
